name: Deploy Artifact to Compute Engine

on:
  workflow_run:
    workflows: ["Build Artifact"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'release'

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Debug GitHub OIDC Claims
        run: |
          echo "Sub: ${{ github.sub }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event.workflow_run.event }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Publish
        run: dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: out

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: out

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_WIF_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Verify Authentication
        run: gcloud auth list

      - name: Copy file to compute engine
        run: |
          gcloud compute scp --recurse out/* ${{secrets.GCE_INSTANCE_NAME}}:${{secrets.GCE_TARGET_PATH}} --zone=${{secrets.GCE_ZONE}}

      - name: Restart Service
        run: |
          gcloud compute ssh ${{secrets.GCE_INSTANCE_NAME}} --zone=${{secrets.GCE_ZONE}} --command="sudo systemctl restart nopCommerce"