name: Build Solution
on:
  repository_dispatch:
    types: [modulel-updated]
  workflow_dispatch:   
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - name: Checkout parent repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.CI_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x      
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build --no-restore --configuration Release src
    - name: Test
      run: dotnet test --no-build --configuration Release --verbisity normal src